<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\$(Configuration)\Mods\mod</OutputPath>
    <GamePath>C:\Users\$(USERNAME)\AppData\Roaming\Vintagestory</GamePath>
    <GamePath Condition="Exists('$(VINTAGE_STORY)')">$(VINTAGE_STORY)</GamePath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(GamePath)\VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VSSurvivalMod">
      <HintPath>$(GamePath)\Mods\VSSurvivalMod.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VSEssentials">
      <HintPath>$(GamePath)\Mods\VSEssentials.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VSCreativeMod">
      <HintPath>$(GamePath)\Mods\VSCreativeMod.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(GamePath)\Lib\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(GamePath)\Lib\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VintagestoryLib">
      <HintPath>$(GamePath)\VintagestoryLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="protobuf-net">
      <HintPath>$(GamePath)\Lib\protobuf-net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="cairo-sharp">
      <HintPath>$(GamePath)\Lib\cairo-sharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Microsoft.Data.Sqlite">
      <HintPath>$(GamePath)\Lib\Microsoft.Data.Sqlite.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

<ItemGroup>
  <Content Include="modinfo.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
</ItemGroup>

    <!--<ItemGroup>
  <Content Include="modicon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
</ItemGroup>-->

</Project>
